#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/CCT?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=db12

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cct
    username: root
    password: db12


  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
     ddl-auto: update
    show_sql: true
    format_sql: true

  swagger:
    enabled: true # Swagger를 활성화합니다.

  springfox:
    documentation:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


swagger-ui:
  enabled: true # Swagger UI를 활성화합니다.
#    default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  # parameter Binding